#!/bin/sh

# Check for proper number of command line args.                                                                                                               
if [ $# != 2 ]; then
  echo "Usage: makeLinks fluidCase solidCase"
  exit 0
fi

cd $1

cd constant

ln -s ../../$2/constant solid

cd ../system

ln -s ../../$2/system solid

cd ../0

ln -s ../../$2/0 solid

cd ../../

