#!/bin/sh

# Check for proper number of command line args.                                                                                                               
if [ $# != 2 ]; then
  echo "Usage: makeLinks fluidCase solidCase"
  exit 0
fi

cd $1

rm -rf 0/solid

rm -rf constant/solid

rm -rf system/solid

cd ..
